---
ID: "76568d17-43ae-4fa4-91d6-571bc94aaa8e"
Parent: "7f7040cb-c096-4183-9e0b-4bf5ae4b3e72"
Template: "51f88703-1880-4e9d-8bc9-b0da310ca074"
Path: "/sitecore/content/demo-tenant/Novena/Home/services"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 150
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{242CC0F8-29F0-4C14-945B-847E8CFBB256}"
              s:id="{E7871019-6743-4C3D-9616-5BE103A82564}"
              s:par="CacheClearingBehavior=Clear on publish"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221228T121339Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "457b0b2f-76db-4af8-883f-04ea85290147"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230102T063953Z
    - ID: "e3be3972-1804-40ef-9e06-ae2c9daeb61a"
      Hint: Title
      Value: Services
