---
ID: "dc871ebf-0821-4f19-b946-39f6866a737d"
Parent: "97f35a4e-bae4-42d6-9db2-a653bf3b90e8"
Template: "97f35a4e-bae4-42d6-9db2-a653bf3b90e8"
Path: "/sitecore/templates/Project/demo-tenant/Headless Tenant/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221226T101941Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cc8ca9f6-8bc7-4b91-9882-f3aaee0691c9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221226T101941Z
