---
ID: "63ff011c-cb14-4bff-b7ec-9b5cb4026a6b"
Parent: "0dfb92e0-6c0c-453d-a795-2fab049fe014"
Template: "0dfb92e0-6c0c-453d-a795-2fab049fe014"
Path: /sitecore/templates/Feature/Novena/Teaser Items Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{F2758BDC-97D2-4D24-8ABD-59AC8E1A1ACB}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230106T084843Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e64671df-c427-4788-b493-0cd2f52becf7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230106T084850Z
